- name: Update apt cache and install Apache web server
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - libapache2-mod-php
    - php
    - php-mysql
    - php-curl
    - php-json
    - php-mbstring
    - nodejs
    - npm
  become: yes

- name: Clone Laravel repository and configure environment
  block:
    - name: Git clone Laravel
      git:
        repo: "https://github.com/Practical-DevOps/app-for-devops.git"
        dest: "/var/www/html/app-for-devops"
        clone: yes
