


    - name: Update apt cache and install Apache web server
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - libapache2-mod-php
        - php
        - php-mysql
        - php-curl
        - php-json
        - php-mbstring
        - nodejs
        - npm
      become: yes
